import type { MockCreator } from "@/lib/types";

const HOUR = 1000 * 60 * 60;
const DAY = HOUR * 24;
const now = Date.now();

function daysAgo(days: number): string {
  return new Date(now - days * DAY).toISOString();
}

function hoursFromNow(hours: number): string {
  return new Date(now + hours * HOUR).toISOString();
}

/**
 * 18 mock creators across all 11 categories. Data is static/local — no
 * network calls. lastSeenMinutes/isOnline are plain fields (not derived
 * from a clock) so sorting stays stable within a session.
 */
export const MOCK_CREATORS: MockCreator[] = [
  {
    id: "c01",
    username: "theolinds",
    category: "Gaming",
    bio: "Co-op strategy sessions and build reviews for competitive gamers.",
    lastSeenMinutes: 0,
    isOnline: true,
    averageReplyMinutes: 4,
    chatPrice: "19.00",
    photoPrice: "8.00",
    videoPrice: "25.00",
    joinedAt: daysAgo(410),
    isNew: false,
    boostEndsAt: hoursFromNow(18),
    isAdult: false,
  },
  {
    id: "c02",
    username: "pixel_priya",
    category: "Gaming",
    bio: "Speedrun tips and controller setup Q&A, one chat at a time.",
    lastSeenMinutes: 46,
    isOnline: false,
    averageReplyMinutes: 22,
    chatPrice: "12.00",
    photoPrice: "6.00",
    videoPrice: "18.00",
    joinedAt: daysAgo(6),
    isNew: true,
    isAdult: false,
  },
  {
    id: "c03",
    username: "inescarvalho",
    category: "Music",
    bio: "Vocal coaching and songwriting feedback, one chat at a time.",
    lastSeenMinutes: 180,
    isOnline: false,
    averageReplyMinutes: 35,
    chatPrice: "19.00",
    photoPrice: "8.00",
    videoPrice: "25.00",
    joinedAt: daysAgo(300),
    isNew: false,
    boostEndsAt: hoursFromNow(4),
    isAdult: false,
  },
  {
    id: "c04",
    username: "beatsbyremy",
    category: "Music",
    bio: "Home-studio mixing critiques and beat-making walkthroughs.",
    lastSeenMinutes: 3,
    isOnline: true,
    averageReplyMinutes: 6,
    chatPrice: "15.00",
    photoPrice: "7.00",
    videoPrice: "20.00",
    joinedAt: daysAgo(120),
    isNew: false,
    isAdult: false,
  },
  {
    id: "c05",
    username: "priyanandan",
    category: "Fitness",
    bio: "Strength training programs and honest supplement Q&A.",
    lastSeenMinutes: 0,
    isOnline: true,
    averageReplyMinutes: 5,
    chatPrice: "22.00",
    photoPrice: "9.00",
    videoPrice: "30.00",
    joinedAt: daysAgo(540),
    isNew: false,
    isAdult: false,
  },
  {
    id: "c06",
    username: "coach_marek",
    category: "Fitness",
    bio: "Mobility and injury-prevention routines for lifters over 30.",
    lastSeenMinutes: 12,
    isOnline: false,
    averageReplyMinutes: 40,
    chatPrice: "18.00",
    photoPrice: "8.00",
    videoPrice: "24.00",
    joinedAt: daysAgo(4),
    isNew: true,
    isAdult: false,
  },
  {
    id: "c07",
    username: "mayaokoye",
    category: "Lifestyle",
    bio: "Slow-living and home-organizing chats for a calmer week.",
    lastSeenMinutes: 0,
    isOnline: true,
    averageReplyMinutes: 8,
    chatPrice: "14.00",
    photoPrice: "6.00",
    videoPrice: "20.00",
    joinedAt: daysAgo(210),
    isNew: false,
    boostEndsAt: hoursFromNow(30),
    isAdult: false,
  },
  {
    id: "c08",
    username: "minimalist_noa",
    category: "Lifestyle",
    bio: "Capsule wardrobes and decluttering, one room at a time.",
    lastSeenMinutes: 260,
    isOnline: false,
    averageReplyMinutes: 60,
    chatPrice: "11.00",
    photoPrice: "5.00",
    videoPrice: "16.00",
    joinedAt: daysAgo(95),
    isNew: false,
    isAdult: false,
  },
  {
    id: "c09",
    username: "danielferris_cpa",
    category: "Expert",
    bio: "Licensed CPA answering small-business tax questions live.",
    lastSeenMinutes: 700,
    isOnline: false,
    averageReplyMinutes: 90,
    chatPrice: "35.00",
    photoPrice: "10.00",
    videoPrice: "45.00",
    joinedAt: daysAgo(430),
    isNew: false,
    isAdult: false,
  },
  {
    id: "c10",
    username: "askdrlin",
    category: "Expert",
    bio: "General wellness questions answered by a licensed nurse practitioner.",
    lastSeenMinutes: 25,
    isOnline: false,
    averageReplyMinutes: 50,
    chatPrice: "28.00",
    photoPrice: "9.00",
    videoPrice: "38.00",
    joinedAt: daysAgo(8),
    isNew: true,
    isAdult: false,
  },
  {
    id: "c11",
    username: "kernelkat",
    category: "Technology",
    bio: "Code review and career advice for early-career engineers.",
    lastSeenMinutes: 1,
    isOnline: true,
    averageReplyMinutes: 7,
    chatPrice: "24.00",
    photoPrice: "8.00",
    videoPrice: "32.00",
    joinedAt: daysAgo(260),
    isNew: false,
    isAdult: false,
  },
  {
    id: "c12",
    username: "buildwithomar",
    category: "Technology",
    bio: "Homelab and self-hosting setups, troubleshot live.",
    lastSeenMinutes: 90,
    isOnline: false,
    averageReplyMinutes: 45,
    chatPrice: "16.00",
    photoPrice: "6.00",
    videoPrice: "22.00",
    joinedAt: daysAgo(2),
    isNew: true,
    isAdult: false,
  },
  {
    id: "c13",
    username: "ms_alvarez_tutors",
    category: "Education",
    bio: "Certified teacher helping with essay structure and study plans.",
    lastSeenMinutes: 15,
    isOnline: false,
    averageReplyMinutes: 30,
    chatPrice: "20.00",
    photoPrice: "7.00",
    videoPrice: "26.00",
    joinedAt: daysAgo(150),
    isNew: false,
    isAdult: false,
  },
  {
    id: "c14",
    username: "coach_delacruz",
    category: "Sports",
    bio: "Youth soccer drills and match-day preparation tips.",
    lastSeenMinutes: 0,
    isOnline: true,
    averageReplyMinutes: 10,
    chatPrice: "17.00",
    photoPrice: "7.00",
    videoPrice: "23.00",
    joinedAt: daysAgo(320),
    isNew: false,
    isAdult: false,
  },
  {
    id: "c15",
    username: "courtside_jamal",
    category: "Sports",
    bio: "Basketball shooting-form breakdowns from film.",
    lastSeenMinutes: 500,
    isOnline: false,
    averageReplyMinutes: 70,
    chatPrice: "13.00",
    photoPrice: "6.00",
    videoPrice: "19.00",
    joinedAt: daysAgo(10),
    isNew: true,
    isAdult: false,
  },
  {
    id: "c16",
    username: "styledby_elle",
    category: "Fashion",
    bio: "Personal styling and outfit-repeat-proof capsule closets.",
    lastSeenMinutes: 40,
    isOnline: false,
    averageReplyMinutes: 25,
    chatPrice: "21.00",
    photoPrice: "9.00",
    videoPrice: "28.00",
    joinedAt: daysAgo(75),
    isNew: false,
    boostEndsAt: hoursFromNow(2),
    isAdult: false,
  },
  {
    id: "c17",
    username: "inkwell_sasha",
    category: "Art",
    bio: "Digital illustration critiques and process walkthroughs.",
    lastSeenMinutes: 5,
    isOnline: true,
    averageReplyMinutes: 12,
    chatPrice: "18.00",
    photoPrice: "8.00",
    videoPrice: "24.00",
    joinedAt: daysAgo(190),
    isNew: false,
    isAdult: false,
  },
  {
    id: "c18",
    username: "rubysinclair",
    category: "Adult 18+",
    bio: "Lawful adult creator. Age-verified, 18+ chat access only.",
    lastSeenMinutes: 2,
    isOnline: true,
    averageReplyMinutes: 6,
    chatPrice: "29.00",
    photoPrice: "15.00",
    videoPrice: "49.00",
    joinedAt: daysAgo(500),
    isNew: false,
    boostEndsAt: hoursFromNow(10),
    isAdult: true,
  },
];
