/**
 * Supabase database types.
 *
 * Regenerated by `npm run supabase:types` (see docs/supabase-setup.md)
 * whenever the schema in supabase/migrations/ changes. This copy was
 * hand-derived from the Phase 2.1B migrations and cross-checked against a
 * real Postgres 16 database the migrations were actually applied to
 * (information_schema.columns), since CLI codegen requires a linked
 * Supabase project this environment doesn't have network access to.
 * Re-run the real generator against your own linked project before
 * trusting this for anything beyond local development.
 */

export type UserRole = "fan" | "creator" | "moderator" | "admin" | "super_admin";
export type ProfileStatus = "active" | "suspended" | "banned" | "deleted";
export type CreatorStatus = "draft" | "pending_review" | "approved" | "rejected" | "suspended";
export type AvailabilityStatus = "available" | "busy" | "offline";
export type ConversationSessionStatus = "pending" | "active" | "expired" | "refunded";
export type PaymentStatus = "pending" | "processing" | "paid" | "failed" | "cancelled" | "expired";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: UserRole;
          username: string | null;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          status: ProfileStatus;
          date_of_birth: string | null;
          country_code: string | null;
          timezone: string | null;
          last_seen_at: string | null;
          onboarding_completed: boolean;
          adult_content_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          role?: UserRole;
          username?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          status?: ProfileStatus;
          date_of_birth?: string | null;
          country_code?: string | null;
          timezone?: string | null;
          last_seen_at?: string | null;
          onboarding_completed?: boolean;
          adult_content_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
        Relationships: [];
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          is_adult: boolean;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          is_adult?: boolean;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["categories"]["Insert"]>;
        Relationships: [];
      };
      creator_profiles: {
        Row: {
          user_id: string;
          status: CreatorStatus;
          headline: string | null;
          about: string | null;
          banner_url: string | null;
          primary_category_id: string | null;
          chat_price_minor: number;
          photo_price_minor: number;
          video_price_minor: number;
          currency_code: string;
          availability: AvailabilityStatus;
          response_rate: number | null;
          average_response_minutes: number | null;
          completed_conversations_count: number;
          returning_fans_count: number;
          profile_views_count: number;
          total_earnings_minor: number;
          joined_creator_at: string;
          approved_at: string | null;
          approved_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          status?: CreatorStatus;
          headline?: string | null;
          about?: string | null;
          banner_url?: string | null;
          primary_category_id?: string | null;
          chat_price_minor?: number;
          photo_price_minor?: number;
          video_price_minor?: number;
          currency_code?: string;
          availability?: AvailabilityStatus;
          response_rate?: number | null;
          average_response_minutes?: number | null;
          completed_conversations_count?: number;
          returning_fans_count?: number;
          profile_views_count?: number;
          total_earnings_minor?: number;
          joined_creator_at?: string;
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["creator_profiles"]["Insert"]>;
        Relationships: [];
      };
      creator_categories: {
        Row: {
          creator_id: string;
          category_id: string;
          is_primary: boolean;
          created_at: string;
        };
        Insert: {
          creator_id: string;
          category_id: string;
          is_primary?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["creator_categories"]["Insert"]>;
        Relationships: [];
      };
      creator_favourites: {
        Row: {
          fan_id: string;
          creator_id: string;
          created_at: string;
        };
        Insert: {
          fan_id: string;
          creator_id: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["creator_favourites"]["Insert"]>;
        Relationships: [];
      };
      conversations: {
        Row: {
          id: string;
          creator_id: string;
          fan_id: string;
          latest_message_at: string | null;
          latest_message_preview: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          creator_id: string;
          fan_id: string;
          latest_message_at?: string | null;
          latest_message_preview?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["conversations"]["Insert"]>;
        Relationships: [];
      };
      conversation_sessions: {
        Row: {
          id: string;
          conversation_id: string;
          activated_at: string;
          expires_at: string;
          status: ConversationSessionStatus;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          activated_at?: string;
          expires_at: string;
          status?: ConversationSessionStatus;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["conversation_sessions"]["Insert"]>;
        Relationships: [];
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          body: string;
          message_type: string;
          client_message_id: string | null;
          created_at: string;
          edited_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender_id: string;
          body: string;
          message_type?: string;
          client_message_id?: string | null;
          created_at?: string;
          edited_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["messages"]["Insert"]>;
        Relationships: [];
      };
      conversation_reads: {
        Row: {
          conversation_id: string;
          user_id: string;
          last_read_message_id: string | null;
          last_read_at: string;
        };
        Insert: {
          conversation_id: string;
          user_id: string;
          last_read_message_id?: string | null;
          last_read_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["conversation_reads"]["Insert"]>;
        Relationships: [];
      };
      user_presence: {
        Row: {
          user_id: string;
          last_seen_at: string | null;
          last_active_at: string | null;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          last_seen_at?: string | null;
          last_active_at?: string | null;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["user_presence"]["Insert"]>;
        Relationships: [];
      };
      payment_attempts: {
        Row: {
          id: string;
          fan_id: string;
          creator_id: string;
          conversation_id: string;
          amount_minor: number;
          currency: string;
          product_type: string;
          internal_status: PaymentStatus;
          provider: string;
          provider_reference: string | null;
          provider_status: string | null;
          client_idempotency_key: string;
          provider_event_id: string | null;
          paid_at: string | null;
          failure_reason: string | null;
          activated_session_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          fan_id: string;
          creator_id: string;
          conversation_id: string;
          amount_minor?: number;
          currency?: string;
          product_type?: string;
          internal_status?: PaymentStatus;
          provider?: string;
          provider_reference?: string | null;
          provider_status?: string | null;
          client_idempotency_key: string;
          provider_event_id?: string | null;
          paid_at?: string | null;
          failure_reason?: string | null;
          activated_session_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["payment_attempts"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: {
      public_creator_profiles: {
        Row: {
          user_id: string;
          username: string | null;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          headline: string | null;
          banner_url: string | null;
          chat_price_minor: number;
          photo_price_minor: number;
          video_price_minor: number;
          currency_code: string;
          availability: AvailabilityStatus;
          response_rate: number | null;
          average_response_minutes: number | null;
          completed_conversations_count: number;
          returning_fans_count: number;
          joined_creator_at: string;
          primary_category_id: string | null;
          primary_category_slug: string | null;
          primary_category_name: string | null;
        };
        Relationships: [];
      };
      public_creator_categories: {
        Row: {
          creator_id: string;
          category_id: string;
          category_slug: string;
          category_name: string;
          is_primary: boolean;
        };
        Relationships: [];
      };
      fan_payment_history: {
        Row: {
          id: string;
          creator_id: string;
          conversation_id: string;
          amount_minor: number;
          currency: string;
          product_type: string;
          internal_status: PaymentStatus;
          provider_reference: string | null;
          provider_status: string | null;
          paid_at: string | null;
          failure_reason: string | null;
          created_at: string;
        };
        Relationships: [];
      };
      creator_payment_summary: {
        Row: {
          id: string;
          fan_id: string;
          conversation_id: string;
          amount_minor: number;
          currency: string;
          product_type: string;
          internal_status: PaymentStatus;
          paid_at: string | null;
          created_at: string;
        };
        Relationships: [];
      };
    };
    Functions: {
      is_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      expire_conversation_sessions: {
        Args: { p_conversation_id: string };
        Returns: undefined;
      };
      touch_presence: {
        Args: Record<string, never>;
        Returns: undefined;
      };
      mark_conversation_read: {
        Args: { p_conversation_id: string; p_message_id?: string | null };
        Returns: undefined;
      };
    };
    Enums: {
      user_role: UserRole;
      profile_status: ProfileStatus;
      creator_status: CreatorStatus;
      availability_status: AvailabilityStatus;
      conversation_session_status: ConversationSessionStatus;
    };
    CompositeTypes: Record<string, never>;
  };
}
