/**
 * Placeholder Supabase database types.
 *
 * This file is regenerated by `npm run supabase:types` (see
 * docs/supabase-setup.md) once a real Supabase project and schema exist.
 * Until then, it defines an intentionally empty schema so the typed
 * clients in lib/supabase/ compile — no tables exist yet, and nothing in
 * the app queries them (Phase 2.1A is foundation-only).
 */

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
