/**
 * Supabase database types.
 *
 * Regenerated by `npm run supabase:types` (see docs/supabase-setup.md)
 * whenever the schema in supabase/migrations/ changes. This copy was
 * hand-derived from the Phase 2.1B migrations and cross-checked against a
 * real Postgres 16 database the migrations were actually applied to
 * (information_schema.columns), since CLI codegen requires a linked
 * Supabase project this environment doesn't have network access to.
 * Re-run the real generator against your own linked project before
 * trusting this for anything beyond local development.
 */

export type UserRole = "fan" | "creator" | "support" | "moderator" | "admin" | "super_admin";
export type ProfileStatus = "active" | "suspended" | "banned" | "deleted";
export type CreatorStatus = "draft" | "pending_review" | "approved" | "rejected" | "suspended";
export type AvailabilityStatus = "available" | "busy" | "offline";
export type ConversationSessionStatus = "pending" | "active" | "expired" | "refunded";
export type PaymentStatus = "pending" | "processing" | "paid" | "failed" | "cancelled" | "expired";
export type ModerationReportType = "user_report" | "creator_report" | "payment_dispute" | "abuse_report" | "spam_report";
export type ModerationReportStatus = "open" | "assigned" | "resolved" | "dismissed";
export type LedgerEntryType =
  | "chat_earning"
  | "platform_commission"
  | "refund"
  | "reversal"
  | "payout_deduction"
  | "manual_adjustment";
export type LedgerSettlementStatus = "pending" | "available";
export type PayoutRequestStatus = "pending" | "approved" | "processing" | "paid" | "rejected" | "cancelled";
export type MediaRequestType = "live_photo" | "live_video";
export type MediaRequestStatus =
  | "pending_payment"
  | "pending_creator"
  | "accepted"
  | "fulfilled"
  | "declined"
  | "expired"
  | "refund_required";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: UserRole;
          username: string | null;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          status: ProfileStatus;
          date_of_birth: string | null;
          country_code: string | null;
          timezone: string | null;
          last_seen_at: string | null;
          onboarding_completed: boolean;
          adult_content_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          role?: UserRole;
          username?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          status?: ProfileStatus;
          date_of_birth?: string | null;
          country_code?: string | null;
          timezone?: string | null;
          last_seen_at?: string | null;
          onboarding_completed?: boolean;
          adult_content_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
        Relationships: [];
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          is_adult: boolean;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          is_adult?: boolean;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["categories"]["Insert"]>;
        Relationships: [];
      };
      creator_profiles: {
        Row: {
          user_id: string;
          status: CreatorStatus;
          headline: string | null;
          about: string | null;
          banner_url: string | null;
          primary_category_id: string | null;
          chat_price_minor: number;
          photo_price_minor: number;
          video_price_minor: number;
          currency_code: string;
          availability: AvailabilityStatus;
          response_rate: number | null;
          average_response_minutes: number | null;
          completed_conversations_count: number;
          returning_fans_count: number;
          profile_views_count: number;
          total_earnings_minor: number;
          joined_creator_at: string;
          approved_at: string | null;
          approved_by: string | null;
          is_verified: boolean;
          commission_tier_id: string | null;
          commission_rate_bps: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          status?: CreatorStatus;
          headline?: string | null;
          about?: string | null;
          banner_url?: string | null;
          primary_category_id?: string | null;
          chat_price_minor?: number;
          photo_price_minor?: number;
          video_price_minor?: number;
          currency_code?: string;
          availability?: AvailabilityStatus;
          response_rate?: number | null;
          average_response_minutes?: number | null;
          completed_conversations_count?: number;
          returning_fans_count?: number;
          profile_views_count?: number;
          total_earnings_minor?: number;
          joined_creator_at?: string;
          approved_at?: string | null;
          approved_by?: string | null;
          is_verified?: boolean;
          commission_tier_id?: string | null;
          commission_rate_bps?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["creator_profiles"]["Insert"]>;
        Relationships: [];
      };
      creator_categories: {
        Row: {
          creator_id: string;
          category_id: string;
          is_primary: boolean;
          created_at: string;
        };
        Insert: {
          creator_id: string;
          category_id: string;
          is_primary?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["creator_categories"]["Insert"]>;
        Relationships: [];
      };
      creator_favourites: {
        Row: {
          fan_id: string;
          creator_id: string;
          created_at: string;
        };
        Insert: {
          fan_id: string;
          creator_id: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["creator_favourites"]["Insert"]>;
        Relationships: [];
      };
      conversations: {
        Row: {
          id: string;
          creator_id: string;
          fan_id: string;
          latest_message_at: string | null;
          latest_message_preview: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          creator_id: string;
          fan_id: string;
          latest_message_at?: string | null;
          latest_message_preview?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["conversations"]["Insert"]>;
        Relationships: [];
      };
      conversation_sessions: {
        Row: {
          id: string;
          conversation_id: string;
          activated_at: string;
          expires_at: string;
          status: ConversationSessionStatus;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          activated_at?: string;
          expires_at: string;
          status?: ConversationSessionStatus;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["conversation_sessions"]["Insert"]>;
        Relationships: [];
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          body: string;
          message_type: string;
          client_message_id: string | null;
          created_at: string;
          edited_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender_id: string;
          body: string;
          message_type?: string;
          client_message_id?: string | null;
          created_at?: string;
          edited_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["messages"]["Insert"]>;
        Relationships: [];
      };
      conversation_reads: {
        Row: {
          conversation_id: string;
          user_id: string;
          last_read_message_id: string | null;
          last_read_at: string;
        };
        Insert: {
          conversation_id: string;
          user_id: string;
          last_read_message_id?: string | null;
          last_read_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["conversation_reads"]["Insert"]>;
        Relationships: [];
      };
      user_presence: {
        Row: {
          user_id: string;
          last_seen_at: string | null;
          last_active_at: string | null;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          last_seen_at?: string | null;
          last_active_at?: string | null;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["user_presence"]["Insert"]>;
        Relationships: [];
      };
      payment_attempts: {
        Row: {
          id: string;
          fan_id: string;
          creator_id: string;
          conversation_id: string;
          amount_minor: number;
          currency: string;
          product_type: string;
          internal_status: PaymentStatus;
          provider: string;
          provider_reference: string | null;
          provider_status: string | null;
          client_idempotency_key: string;
          provider_event_id: string | null;
          paid_at: string | null;
          failure_reason: string | null;
          activated_session_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          fan_id: string;
          creator_id: string;
          conversation_id: string;
          amount_minor?: number;
          currency?: string;
          product_type?: string;
          internal_status?: PaymentStatus;
          provider?: string;
          provider_reference?: string | null;
          provider_status?: string | null;
          client_idempotency_key: string;
          provider_event_id?: string | null;
          paid_at?: string | null;
          failure_reason?: string | null;
          activated_session_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["payment_attempts"]["Insert"]>;
        Relationships: [];
      };
      payment_webhook_events: {
        Row: {
          id: string;
          provider: string;
          received_at: string;
          signature_valid: boolean;
          provider_event_id: string | null;
          payment_attempt_id: string | null;
          outcome: string;
          body_sha256: string;
          header_names: string | null;
        };
        Insert: {
          id?: string;
          provider: string;
          received_at?: string;
          signature_valid: boolean;
          provider_event_id?: string | null;
          payment_attempt_id?: string | null;
          outcome: string;
          body_sha256: string;
          header_names?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["payment_webhook_events"]["Insert"]>;
        Relationships: [];
      };
      admin_audit_log: {
        Row: {
          id: string;
          actor_id: string;
          action: string;
          target_type: string;
          target_id: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id: string;
          action: string;
          target_type: string;
          target_id?: string | null;
          metadata?: Record<string, unknown>;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["admin_audit_log"]["Insert"]>;
        Relationships: [];
      };
      moderation_reports: {
        Row: {
          id: string;
          report_type: ModerationReportType;
          reporter_id: string | null;
          reported_user_id: string | null;
          reported_creator_id: string | null;
          payment_attempt_id: string | null;
          conversation_id: string | null;
          reason: string;
          status: ModerationReportStatus;
          assigned_to: string | null;
          notes: string | null;
          created_at: string;
          resolved_at: string | null;
        };
        Insert: {
          id?: string;
          report_type: ModerationReportType;
          reporter_id?: string | null;
          reported_user_id?: string | null;
          reported_creator_id?: string | null;
          payment_attempt_id?: string | null;
          conversation_id?: string | null;
          reason: string;
          status?: ModerationReportStatus;
          assigned_to?: string | null;
          notes?: string | null;
          created_at?: string;
          resolved_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["moderation_reports"]["Insert"]>;
        Relationships: [];
      };
      user_blocks: {
        Row: {
          id: string;
          blocker_id: string;
          blocked_id: string;
          reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          blocker_id: string;
          blocked_id: string;
          reason?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["user_blocks"]["Insert"]>;
        Relationships: [];
      };
      platform_settings: {
        Row: { key: string; value: unknown; updated_at: string; updated_by: string | null };
        Insert: { key: string; value: unknown; updated_at?: string; updated_by?: string | null };
        Update: Partial<Database["public"]["Tables"]["platform_settings"]["Insert"]>;
        Relationships: [];
      };
      creator_commission_tiers: {
        Row: { id: string; name: string; commission_bps: number; created_at: string };
        Insert: { id?: string; name: string; commission_bps: number; created_at?: string };
        Update: Partial<Database["public"]["Tables"]["creator_commission_tiers"]["Insert"]>;
        Relationships: [];
      };
      creator_ledger_entries: {
        Row: {
          id: string;
          creator_id: string;
          entry_type: LedgerEntryType;
          source_payment_id: string | null;
          source_conversation_id: string | null;
          source_session_id: string | null;
          gross_amount_minor: number;
          platform_fee_minor: number;
          creator_net_minor: number;
          currency: string;
          commission_rate_bps: number | null;
          settlement_status: LedgerSettlementStatus;
          payout_id: string | null;
          reverses_entry_id: string | null;
          metadata: Record<string, unknown>;
          reference: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          creator_id: string;
          entry_type: LedgerEntryType;
          source_payment_id?: string | null;
          source_conversation_id?: string | null;
          source_session_id?: string | null;
          gross_amount_minor?: number;
          platform_fee_minor?: number;
          creator_net_minor: number;
          currency: string;
          commission_rate_bps?: number | null;
          settlement_status?: LedgerSettlementStatus;
          payout_id?: string | null;
          reverses_entry_id?: string | null;
          metadata?: Record<string, unknown>;
          reference?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["creator_ledger_entries"]["Insert"]>;
        Relationships: [];
      };
      creator_payout_destinations: {
        Row: { id: string; creator_id: string; label: string; masked_reference: string | null; is_default: boolean; created_at: string };
        Insert: {
          id?: string;
          creator_id: string;
          label: string;
          masked_reference?: string | null;
          is_default?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["creator_payout_destinations"]["Insert"]>;
        Relationships: [];
      };
      creator_payout_requests: {
        Row: {
          id: string;
          creator_id: string;
          amount_minor: number;
          currency: string;
          status: PayoutRequestStatus;
          destination_id: string | null;
          requested_at: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
          completed_at: string | null;
          admin_notes: string | null;
        };
        Insert: {
          id?: string;
          creator_id: string;
          amount_minor: number;
          currency: string;
          status?: PayoutRequestStatus;
          destination_id?: string | null;
          requested_at?: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          completed_at?: string | null;
          admin_notes?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["creator_payout_requests"]["Insert"]>;
        Relationships: [];
      };
      media_requests: {
        Row: {
          id: string;
          conversation_id: string;
          fan_id: string;
          creator_id: string;
          request_type: MediaRequestType;
          amount_minor: number;
          currency: string;
          status: MediaRequestStatus;
          payment_attempt_id: string | null;
          storage_path: string | null;
          requested_at: string;
          responded_at: string | null;
          fulfilled_at: string | null;
          expires_at: string | null;
          decline_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          fan_id: string;
          creator_id: string;
          request_type: MediaRequestType;
          amount_minor: number;
          currency: string;
          status?: MediaRequestStatus;
          payment_attempt_id?: string | null;
          storage_path?: string | null;
          requested_at?: string;
          responded_at?: string | null;
          fulfilled_at?: string | null;
          expires_at?: string | null;
          decline_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["media_requests"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: {
      creator_balances: {
        Row: {
          creator_id: string;
          currency: string;
          pending_balance_minor: number;
          available_balance_minor: number;
          paid_out_minor: number;
          lifetime_gross_minor: number;
          lifetime_creator_earnings_minor: number;
          lifetime_platform_fees_minor: number;
        };
        Relationships: [];
      };
      public_creator_profiles: {
        Row: {
          user_id: string;
          username: string | null;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          headline: string | null;
          banner_url: string | null;
          chat_price_minor: number;
          photo_price_minor: number;
          video_price_minor: number;
          currency_code: string;
          availability: AvailabilityStatus;
          response_rate: number | null;
          average_response_minutes: number | null;
          completed_conversations_count: number;
          returning_fans_count: number;
          joined_creator_at: string;
          primary_category_id: string | null;
          primary_category_slug: string | null;
          primary_category_name: string | null;
        };
        Relationships: [];
      };
      public_creator_categories: {
        Row: {
          creator_id: string;
          category_id: string;
          category_slug: string;
          category_name: string;
          is_primary: boolean;
        };
        Relationships: [];
      };
      fan_payment_history: {
        Row: {
          id: string;
          creator_id: string;
          conversation_id: string;
          amount_minor: number;
          currency: string;
          product_type: string;
          internal_status: PaymentStatus;
          provider_reference: string | null;
          provider_status: string | null;
          paid_at: string | null;
          failure_reason: string | null;
          created_at: string;
        };
        Relationships: [];
      };
      creator_payment_summary: {
        Row: {
          id: string;
          fan_id: string;
          conversation_id: string;
          amount_minor: number;
          currency: string;
          product_type: string;
          internal_status: PaymentStatus;
          paid_at: string | null;
          created_at: string;
        };
        Relationships: [];
      };
    };
    Functions: {
      is_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      is_staff: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      is_privileged_staff: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      is_super_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      log_admin_action: {
        Args: { p_action: string; p_target_type: string; p_target_id?: string | null; p_metadata?: Record<string, unknown> };
        Returns: string;
      };
      expire_conversation_sessions: {
        Args: { p_conversation_id: string };
        Returns: undefined;
      };
      touch_presence: {
        Args: Record<string, never>;
        Returns: undefined;
      };
      mark_conversation_read: {
        Args: { p_conversation_id: string; p_message_id?: string | null };
        Returns: undefined;
      };
      settle_matured_ledger_entries: {
        Args: Record<string, never>;
        Returns: undefined;
      };
      request_payout: {
        Args: { p_amount_minor: number; p_currency: string; p_destination_id?: string | null };
        Returns: string;
      };
      cancel_payout_request: {
        Args: { p_payout_id: string };
        Returns: undefined;
      };
      approve_payout: {
        Args: { p_payout_id: string; p_notes?: string | null };
        Returns: undefined;
      };
      reject_payout: {
        Args: { p_payout_id: string; p_reason: string };
        Returns: undefined;
      };
      mark_payout_processing: {
        Args: { p_payout_id: string };
        Returns: undefined;
      };
      mark_payout_paid: {
        Args: { p_payout_id: string; p_notes?: string | null };
        Returns: undefined;
      };
      reverse_ledger_earning: {
        Args: { p_ledger_entry_id: string; p_reason: string };
        Returns: string;
      };
      create_media_request: {
        Args: { p_conversation_id: string; p_request_type: MediaRequestType };
        Returns: string;
      };
      accept_media_request: {
        Args: { p_media_request_id: string };
        Returns: undefined;
      };
      decline_media_request: {
        Args: { p_media_request_id: string; p_reason?: string | null };
        Returns: undefined;
      };
      fulfil_media_request: {
        Args: { p_media_request_id: string; p_storage_path: string };
        Returns: undefined;
      };
      expire_stale_media_requests: {
        Args: Record<string, never>;
        Returns: undefined;
      };
    };
    Enums: {
      user_role: UserRole;
      profile_status: ProfileStatus;
      creator_status: CreatorStatus;
      availability_status: AvailabilityStatus;
      conversation_session_status: ConversationSessionStatus;
    };
    CompositeTypes: Record<string, never>;
  };
}
